[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

# space + go -> exec
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
map <Leader>go :QuickRun<CR>
let g:quickrun_config={'*': {'split': ''}}
'''

# ga -> align
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

# Color scheme
[[plugins]]
repo='morhetz/gruvbox'
[[plugins]]
repo = 'whatyouhide/vim-gotham'
hook_add = '''
syntax enable
colorscheme gotham256
'''

# é–‰ã˜æ‹¬å¼§ä¿ç®¡
[[plugins]]
repo = 'cohama/lexima.vim'

# Markdown
[[plugins]]
repo = 'previm/previm'
hook_add = '''
nnoremap <silent> <C-p> :PrevimOpen<CR>
let g:vim_markdown_folding_disabled = 1
let g:previm_enable_realtime = 1
'''
[[plugins]]
repo = 'tyru/open-browser.vim'


[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
" ä¿å­˜æ™‚ã®ã¿å®Ÿè¡Œã™ã‚‹
let g:ale_lint_on_text_changed = 0
" è¡¨ç¤ºã«é–¢ã™ã‚‹è¨­å®š
let g:ale_sign_error = 'ï—'
let g:ale_sign_warning = 'ï±'
let g:airline#extensions#ale#open_lnum_symbol = '('
let g:airline#extensions#ale#close_lnum_symbol = ')'
let g:ale_echo_msg_format = '[%linter%]%code: %%s'
highlight link ALEErrorSign Tag
highlight link ALEWarningSign StorageClass
'''

# spell check
[[plugins]]
repo = 'kamykn/spelunker.vim'

# Twitter
[[plugins]]
repo = 'twitvim/twitvim'

## fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install'
[[plugins]]
repo = 'junegunn/fzf.vim'

## -----*----- NERDTree -----*----- ##
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
" space + dir -> sidebar
let g:NERDTreeChDirMode=2
let g:NERDTreeIgnore=['\.rbc$', '\~$', '\.pyc$', '\.db$', '\.sqlite$', '__pycache__']
let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\.bak$', '\~$']
let g:NERDTreeShowBookmarks=1
let g:nerdtree_tabs_focus_on_files=1
let g:NERDTreeMapOpenInTabSilent = '<RightMouse>'
let g:NERDTreeWinSize = 30
let NERDTreeShowHidden=1
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite
autocmd BufWritePre * :FixWhitespace
let g:NERDTreeMapOpenInTab='d'
map <Leader>dir :NERDTreeToggle<CR>
'''
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
[[plugins]]
repo = 'ryanoasis/vim-devicons'

## -----*----- option bar -----*----- ##
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1
let g:airline#extensions#term#enabled = 0
let g:airline#extensions#whitespace#enabled = 0
let g:airline_theme = 'dark'
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.crypt = 'ğŸ”’'
let g:airline_symbols.linenr = 'âŠ'
let g:airline_symbols.linenr = 'â¤'
let g:airline_symbols.linenr = 'Â¶'
let g:airline_symbols.maxlinenr = 'â˜°'
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.paste = 'Ï'
let g:airline_symbols.paste = 'Ã'
let g:airline_symbols.paste = 'âˆ¥'
let g:airline_symbols.spell = 'ê¨'
let g:airline_symbols.notexists = 'âˆ„'
let g:airline_symbols.whitespace = 'Î'
let g:airline_left_sep = 'î‚°'
let g:airline_left_alt_sep = 'î‚±'
let g:airline_right_sep = 'î‚²'
let g:airline_right_alt_sep = 'î‚³'
let g:airline_symbols.branch = 'î‚ '
let g:airline_symbols.readonly = 'î‚¢'
let g:airline_symbols.linenr = 'î‚¡'
'''
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

## -----*----- ã‚³ãƒ¼ãƒ‰è£œå®Œ -----*----- ##
[[plugins]]
repo = 'sheerun/vim-polyglot'
[[plugins]]
repo = 'ervandew/supertab'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = './install.sh nightly'
hook_add = '''
""Diagnosticsã®ã€å·¦æ¨ªã®ã‚¢ã‚¤ã‚³ãƒ³ã®è‰²è¨­å®š
highlight CocErrorSign ctermfg=15 ctermbg=196
highlight CocWarningSign ctermfg=0 ctermbg=172

""ä»¥ä¸‹ã‚·ãƒ§ãƒ¼ãƒˆã‚«ãƒƒãƒˆ
"ãƒãƒ¼ãƒãƒ«ãƒ¢ãƒ¼ãƒ‰ã§
"ã‚¹ãƒšãƒ¼ã‚¹2å›ã§CocList
nmap <silent> <space><space> :<C-u>CocList<cr>
"ã‚¹ãƒšãƒ¼ã‚¹hã§Hover
nmap <silent> <space>h :<C-u>call CocAction('doHover')<cr>
"ã‚¹ãƒšãƒ¼ã‚¹dfã§Definition
nmap <silent> <space>df <Plug>(coc-definition)
"ã‚¹ãƒšãƒ¼ã‚¹rfã§References
nmap <silent> <space>rf <Plug>(coc-references)
"ã‚¹ãƒšãƒ¼ã‚¹rnã§Rename
nmap <silent> <space>rn <Plug>(coc-rename)
"ã‚¹ãƒšãƒ¼ã‚¹fmtã§Format
nmap <silent> <space>fmt <Plug>(coc-format)
'''

## -----*----- Gité–¢é€£ -----*----- ##
[[plugins]]
repo ='lambdalisue/gina.vim'
hook_add = '''
call gina#custom#command#option('status', '--opener', 'vsplit')
call gina#custom#command#option('diff', '--opener', 'vsplit')
'''

## -----*----- HTML -----*----- ##
[[plugins]]
repo = 'alvan/vim-closetag'
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
[[plugins]]
repo = 'tpope/vim-haml'
[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'kazukazuinaina/Weather.vim'

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'andymass/vim-matchup'
